### ISSUE TITLE
signup and confirm with mail 

### ISSUE THREAD

**Issue by quocbang** [quocbang/data-flow-sync#2]

**Comment by leducthai** [comment]
@quocbang  ủa cái repo chưa có j hết hả

**Comment by quocbang** [comment]
> @quocbang I think you haven't pushed the master branch

yes, I'm do it now, wait a minute

**Comment by quocbang** [comment]
@leducthai I have pushed, please check

**Comment by quocbang** [comment]
@leducthai phần login với phần tạo user thì t sẽ làm chung luôn rồi m chỉ cần gọi qua là được
