### ISSUE TITLE
lam quen voi Swagger & yaml, tao api station va luu vao database

### ISSUE THREAD

**Issue by quocbang** [quocbang/data-flow-sync#4]

**Comment by caosown** [comment]
@quocbang cái này có làm protobuf ko

**Comment by quocbang** [comment]
> @quocbang cái này có làm protobuf ko

không anh, cái này sửa file swagger.yml sau đó vào /server/swagger_gen.go ấn chạy là nó tự gennerate ra

**Comment by caosown** [comment]
@quocbang anh chua co quyen push

**Comment by quocbang** [comment]
@caosown sao vậy được, anh sửa lại mail trên .gitconfig chưa, hay đang mail kenda?

**Comment by caosown** [comment]
@quocbang a mail kenda fuck

**Comment by caosown** [comment]
@quocbang 

![Image](https://github.com/quocbang/data-flow-sync/assets/137710949/ab261094-f92b-44d9-9ab0-523a2526e055)

**Comment by quocbang** [comment]
> @quocbang
> 
> ![Image](https://user-images.githubusercontent.com/137710949/261226005-ab261094-f92b-44d9-9ab0-523a2526e055.png)

anh đặt đúng mail này với tạo nhanh chưa a
